# GitHub actions yaml file to test the app fastapi
name: CI/CD

on:
  push:
    branches:
      - master
      - main
  pull_request:
    branches:
      - main
      - master
  workflow_dispatch:

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12']

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    # once testing is done, build the docker image and push to GitHub container registry
  publish:
    needs: test
    runs-on: ubuntu-latest
    steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Python
          uses: actions/setup-python@v2
          with:
              python-version: '3.9'

        - name: Install dependencies
          run: |
            python -m pip install --upgrade pip
            pip install -r requirements.txt

        - name: Build and push Docker image
          env:
            GHCR_PAT: ${{ secrets.GHCR_TOKEN }}
          run: |
            echo $GHCR_PAT | docker login ghcr.io -u ${{ github.actor }} --password-stdin
            docker build -t ghcr.io/${{ github.repository }}:latest .
            docker push ghcr.io/${{ github.repository }}:latest
    
